Implemented filtering of inclusions & exclusions with svndumpfilter

diff --git a/svnsplit b/svnsplit
--- a/svnsplit
+++ b/svnsplit
@@ -175,10 +175,44 @@ function repo_split() {
 
   # create an svn dump to filter
   local dump_file="${temp_dir}/$(basename "${local_repo}").svndump"
-  if $verbose; then echo "Dumping '${local_repo}' svn repo to '${dump_file}' for processing..."; fi
+  if $verbose; then echo "Dumping '${local_repo}' svn repo to '${dump_file}' for filtering..."; fi
   if ! svnadmin dump "${local_repo}" > "${dump_file}"; then
     success=false
     echo "ERROR! An unknown error occurred while dumping subversion repo!"
+  fi
+
+  # build svndumpfilter command for inclusions
+  local filter_cmd=("svndumpfilter" "--drop-empty-revs" "--renumber-revs")
+  if [ "${#inclusions[@]}" -gt 0 ]; then
+    filter_cmd+=("include")
+    for inclusion in "${inclusions[@]}"; do
+      filter_cmd+=("${inclusion}")
+    done
+  fi
+
+  # filter svn dump for inclusions
+  local inclusions_filtered_file="${temp_dir}/$(basename "${local_repo}").filtered.inclusions.svndump"
+  if $verbose; then echo "Filtering '${dump_file}' with inclusions..."; fi
+  if ! "${filter_cmd[@]}" < "${dump_file}" > "${inclusions_filtered_file}"; then
+    success=false
+    echo "ERROR! An unknown error occurred while filtering the subversion dump file with inclusions!"
+  fi
+
+  # build svndumpfilter command for exclusions
+  local filter_cmd=("svndumpfilter" "--drop-empty-revs" "--renumber-revs")
+  if [ "${#exclusions[@]}" -gt 0 ]; then
+    filter_cmd+=("exclude")
+    for exclusion in "${exclusions[@]}"; do
+      filter_cmd+=("${exclusion}")
+    done
+  fi
+
+  # filter svn dump for exclusions
+  local exclusions_filtered_file="${temp_dir}/$(basename "${local_repo}").filtered.exclusions.svndump"
+  if $verbose; then echo "Filtering '${inclusions_filtered_file}' with exclusions..."; fi
+  if ! "${filter_cmd[@]}" < "${inclusions_filtered_file}" > "${exclusions_filtered_file}"; then
+    success=false
+    echo "ERROR! An unknown error occurred while filtering the subversion dump file with exclusions!"
   fi
 
   
